#!/bin/bash
# Cloud-init user-data run as root on first boot of the EC2 instance.
# Idempotent: re-running should be a no-op once installation is complete.

set -euo pipefail

# Tee everything to a file so the operator can grep it after SSH-ing in.
exec > >(tee -a /var/log/bootstrap.log) 2>&1

echo ""
echo "============================================================"
echo "[bootstrap] $(date -u): start"
echo "============================================================"

INSTALL_DIR=/opt/crypto-bot
REPO_URL="${repo_url}"
REPO_BRANCH="${repo_branch}"

# ----- 1. System packages ----------------------------------------------------

export DEBIAN_FRONTEND=noninteractive

# Wait if the cloud-init managed apt-daily lock is still held.
for i in $(seq 1 60); do
    if ! fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; then
        break
    fi
    echo "[bootstrap] waiting for apt lock... ($i)"
    sleep 5
done

apt-get update -y
apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    gnupg \
    git \
    tini \
    jq \
    htop \
    unattended-upgrades

# ----- 2. Docker engine + compose plugin (official Docker repo) --------------

if ! command -v docker >/dev/null 2>&1; then
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
        | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg

    arch="$(dpkg --print-architecture)"
    codename="$(. /etc/os-release && echo "$VERSION_CODENAME")"
    echo "deb [arch=$arch signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $codename stable" \
        > /etc/apt/sources.list.d/docker.list

    apt-get update -y
    apt-get install -y \
        docker-ce \
        docker-ce-cli \
        containerd.io \
        docker-buildx-plugin \
        docker-compose-plugin
fi

systemctl enable --now docker

# ----- 3. Service user (matches the UID used inside the Dockerfile) ----------
# On Ubuntu 24.04 AMIs the default `ubuntu` user already owns UID 1000,
# which matches the `bot:1000` user created inside the container. So we
# reuse `ubuntu` rather than creating a second UID-1000 user (which fails).

usermod -aG docker ubuntu

# ----- 4. Clone the repo into /opt -------------------------------------------

if [ ! -d "$INSTALL_DIR/.git" ]; then
    rm -rf "$INSTALL_DIR"
    git clone --branch "$REPO_BRANCH" --depth 1 "$REPO_URL" "$INSTALL_DIR"
else
    echo "[bootstrap] repo already cloned, fetching latest on $REPO_BRANCH"
    git -C "$INSTALL_DIR" fetch --depth 1 origin "$REPO_BRANCH"
    git -C "$INSTALL_DIR" reset --hard "origin/$REPO_BRANCH"
fi
chown -R ubuntu:ubuntu "$INSTALL_DIR"

# ----- 5. Pre-create runtime dirs (mounted into the container) ---------------

sudo -u ubuntu mkdir -p "$INSTALL_DIR/data" "$INSTALL_DIR/logs"

# ----- 6. .env placeholder (operator MUST fill before starting the bot) ------

if [ ! -f "$INSTALL_DIR/.env" ]; then
    sudo -u ubuntu cp "$INSTALL_DIR/.env.example" "$INSTALL_DIR/.env"
    chmod 600 "$INSTALL_DIR/.env"
    chown ubuntu:ubuntu "$INSTALL_DIR/.env"
fi

# ----- 7. docker-compose override that runs the actual bot -------------------
# The base docker-compose.yml ships with command=["--help"] so dev users can
# `docker compose run` ad-hoc. In production we want the bot loop. Compose
# auto-merges *.override.yml on `up`, so this flips the default command.

cat > "$INSTALL_DIR/docker-compose.override.yml" <<'OVERRIDE_EOF'
# Auto-generated by Terraform user-data. Edit at your own risk.
services:
  bot:
    command: ["run", "--poll", "1800"]
    restart: unless-stopped
OVERRIDE_EOF
chown ubuntu:ubuntu "$INSTALL_DIR/docker-compose.override.yml"

# ----- 8. Pre-build the image (warm cache so first `up` is fast) -------------

cd "$INSTALL_DIR"
sudo -u ubuntu docker compose build || \
    echo "[bootstrap] WARN: docker build failed; you'll need to retry it manually"

# ----- 9. Unattended security upgrades for the base OS -----------------------

dpkg-reconfigure --priority=low unattended-upgrades || true

# ----- 10. Marker file -------------------------------------------------------

date -u > /opt/bootstrap-complete

echo ""
echo "============================================================"
echo "[bootstrap] $(date -u): done"
echo ""
echo "Next steps for the operator:"
echo "  1. ssh into the VM"
echo "  2. vim $INSTALL_DIR/.env  (add Binance + Telegram tokens)"
echo "  3. cd $INSTALL_DIR && docker compose up -d"
echo "  4. docker compose logs -f"
echo "============================================================"
